project: renpensions
service: cms2
image: %%CI_REGISTRY%%/%%CI_PROJECT_PATH%%
version: %%CI_COMMIT_SHA%%
fullnameOverride: cms2
nameOverride: cms2
#gl_environment_slug: %%CI_ENVIRONMENT_SLUG%%
gl_commit_ref_slug: %%CI_COMMIT_REF_SLUG%%
gl_project_path_slug: %%CI_PROJECT_PATH_SLUG%%
ingress_domain: k8s.dev.local
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 3
    memory: 3096Mi
environment:
  REMOTE_PG_USER: dbcreator
  REMOTE_PG_HOST: 10.91.29.57
  REMOTE_PG_PORT: 5432
  REMOTE_PG_DEFAULT_DATABASE_NAME: dbcreator
  REMOTE_PG_DATABASE_NAME: renpensions_cms2
  SHARED_FOLDER: /mnt/cms2

